Update dependencies
runtimeverification/rv-monitor pull request #19
Opened 2020-11-30 20:42 UTC by mylibero

Signed-off-by: Dongyun Jin <dongyuj@amazon.com>

2020-11-30 20:52 UTC, owolabileg requested changes

2020-11-30 20:52 UTC, owolabileg commented on pom.xml
> +        </dependency>
These seem to new dependencies rather than updates to existing ones. Perhaps the commit message can say why we need the new dependencies?

2020-11-30 20:58 UTC, mylibero commented
Build fails on Mac using Java 15.

For logicrepository, "javax.xml.bind" is needed since it is no longer included in Java 15.
For ptltl, there is an on-going effort to resolve the following error message.
```
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1374)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1278)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:55)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```

2020-12-01 00:08 UTC, mylibero commented
I found no solution to solve the above error message, using Java 15.
Using Java 8 does not have the problem. 

This PR can be ignored if we use Java 8 since "javax.xml.bind" is included in Java 8.

2020-12-01 00:08 UTC, closed without merging